services:
  - type: web
    name: dr-desai-backend
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://drdesaipalus.com,https://www.drdesaipalus.com

  - type: web
    name: dr-desai-frontend
    env: static
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    rootDir: .
    envVars:
      - key: VITE_API_URL
        value: https://dr-desai-backend.onrender.com
